[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"

    # All the feeds we wish to gather for use in the build


    [[plugins.inputs.feeds]]
      name = "RNOTIVE"
      url = "https://remotive.io/api/remote-jobs"
      ttl = 86400